/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness probe */
    get: operations["readyz_readyz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/platform/mode": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Authoritative trading-mode state */
    get: operations["platform_mode_v1_platform_mode_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The calling user and their workspaces */
    get: operations["me_v1_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the caller's workspaces */
    get: operations["list_workspaces_v1_workspaces_get"];
    put?: never;
    /**
     * Create a workspace
     * @description Create a workspace with the caller as its owner.
     *
     *     Not idempotency-keyed: idempotency records are themselves tenant-scoped, and there is no
     *     tenant yet. The unique slug constraint is what makes a retry safe here.
     */
    post: operations["create_workspace_v1_workspaces_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get one workspace
     * @description Read a workspace the caller belongs to.
     *
     *     Membership is already proven by resolving the context; a non-member never reaches this body.
     */
    get: operations["get_workspace_v1_workspaces__workspace_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/agents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List agents */
    get: operations["list_agents_v1_workspaces__workspace_id__agents_get"];
    put?: never;
    /** Create an agent and its first version */
    post: operations["create_agent_v1_workspaces__workspace_id__agents_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/agents/{agent_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get an agent */
    get: operations["get_agent_v1_workspaces__workspace_id__agents__agent_id__get"];
    put?: never;
    post?: never;
    /**
     * Archive an agent
     * @description Archive, never delete: the agent's versions explain its historical decisions.
     */
    delete: operations["archive_agent_v1_workspaces__workspace_id__agents__agent_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/agents/{agent_id}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List agent versions, newest first */
    get: operations["list_versions_v1_workspaces__workspace_id__agents__agent_id__versions_get"];
    put?: never;
    /**
     * Create a new immutable version
     * @description Append a version. The previous version is untouched and remains readable.
     */
    post: operations["create_version_v1_workspaces__workspace_id__agents__agent_id__versions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/agents/{agent_id}/versions/{version}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one version with its full specification */
    get: operations["get_version_v1_workspaces__workspace_id__agents__agent_id__versions__version__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs */
    get: operations["runs_v1_workspaces__workspace_id__runs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Run Detail */
    get: operations["run_detail_v1_workspaces__workspace_id__runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/paper/accounts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Accounts */
    get: operations["accounts_v1_workspaces__workspace_id__paper_accounts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Audit */
    get: operations["audit_v1_workspaces__workspace_id__audit_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/agents/{agent_id}/versions/{version}/rehearsals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Launch an execution-disabled local paper rehearsal */
    post: operations["launch_rehearsal_v1_workspaces__workspace_id__agents__agent_id__versions__version__rehearsals_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/paper/policy-bundles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List paper-policy candidates */
    get: operations["list_paper_policy_bundles_v1_workspaces__workspace_id__paper_policy_bundles_get"];
    put?: never;
    /** Store an immutable, unapproved paper-policy candidate pair */
    post: operations["create_paper_policy_bundle_v1_workspaces__workspace_id__paper_policy_bundles_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/paper/policy-bundles/{bundle_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read a paper-policy candidate */
    get: operations["get_paper_policy_bundle_v1_workspaces__workspace_id__paper_policy_bundles__bundle_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/paper/policy-bundles/{bundle_id}/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the non-activating review recommendation for a policy candidate */
    get: operations["get_paper_policy_review_v1_workspaces__workspace_id__paper_policy_bundles__bundle_id__review_get"];
    put?: never;
    /** Record a second-person policy review recommendation without activation */
    post: operations["review_paper_policy_bundle_v1_workspaces__workspace_id__paper_policy_bundles__bundle_id__review_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/paper/policy-bundles/{bundle_id}/approval": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the non-activating approval for a paper-policy candidate */
    get: operations["get_paper_policy_approval_v1_workspaces__workspace_id__paper_policy_bundles__bundle_id__approval_get"];
    put?: never;
    /** Approve the exact reviewed paper policies without activating execution */
    post: operations["approve_paper_policy_bundle_v1_workspaces__workspace_id__paper_policy_bundles__bundle_id__approval_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/agents/{agent_id}/versions/{version}/paper-activation-assessments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Record a fail-closed paper-activation eligibility assessment */
    post: operations["assess_paper_activation_v1_workspaces__workspace_id__agents__agent_id__versions__version__paper_activation_assessments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workspaces/{workspace_id}/agents/{agent_id}/versions/{version}/paper-activation-assessments/{assessment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one immutable paper-activation eligibility assessment */
    get: operations["get_paper_activation_assessment_v1_workspaces__workspace_id__agents__agent_id__versions__version__paper_activation_assessments__assessment_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AgentCreate
     * @description Create an agent and its first version.
     *
     *     The spec is validated as a full :class:`kavrigo_domain.AgentSpec` before anything is
     *     written, so an invalid configuration never reaches the database or a run.
     */
    AgentCreate: {
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      spec: components["schemas"]["AgentSpec"];
      /**
       * Change Summary
       * @default Initial version.
       */
      change_summary: string;
      /** @default human */
      author_kind: components["schemas"]["AuthorKind"];
    };
    /**
     * AgentDecision
     * @description A validated proposal bound to server-owned context by the agent runtime. Not an order.
     */
    AgentDecision: {
      market_regime: components["schemas"]["MarketRegime"];
      state: components["schemas"]["DecisionState"];
      signals: components["schemas"]["SignalScores"];
      prediction: components["schemas"]["Prediction"];
      proposed_action: components["schemas"]["ProposedAction"];
      proposed_notional?: components["schemas"]["Money"] | null;
      /**
       * Rationale
       * @default
       */
      rationale: string;
      /**
       * Evidence Refs
       * @default []
       */
      evidence_refs: string[];
      /**
       * Contradicting Evidence Refs
       * @default []
       */
      contradicting_evidence_refs: string[];
      /**
       * Risk Flags
       * @default []
       */
      risk_flags: string[];
      /**
       * Reason Codes
       * @default []
       */
      reason_codes: string[];
      /** Estimated Cost Bps */
      estimated_cost_bps?: string | null;
      /**
       * Decision Id
       * @description dec_ id
       */
      decision_id: string;
      /**
       * Workspace Id
       * @description ws_ id
       */
      workspace_id: string;
      /**
       * Agent Version Id
       * @description av_ id
       */
      agent_version_id: string;
      /**
       * Snapshot Id
       * @description snap_ id
       */
      snapshot_id: string;
      instrument_id: components["schemas"]["InstrumentId"];
      /**
       * Decided At
       * Format: date-time
       */
      decided_at: string;
      /**
       * Model Calls
       * @default []
       */
      model_calls: components["schemas"]["ModelCallRecord"][];
    };
    /** AgentResponse */
    AgentResponse: {
      /** Agent Id */
      agent_id: string;
      /** Workspace Id */
      workspace_id: string;
      /** Name */
      name: string;
      /** Description */
      description: string;
      /** Current Version */
      current_version: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      /** Archived At */
      archived_at?: string | null;
    };
    /**
     * AgentSpec
     * @description The declarative agent specification a user reviews and approves.
     */
    AgentSpec: {
      /**
       * Api Version
       * @default agents.kavrigo/v1
       */
      api_version: string;
      /**
       * Kind
       * @default TradingAgent
       */
      kind: string;
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      /** @default paper */
      mode: components["schemas"]["TradingMode"];
      universe: components["schemas"]["UniverseConfig"];
      schedule: components["schemas"]["ScheduleConfig"];
      /** Data Packs */
      data_packs: components["schemas"]["DataPack"][];
      /**
       * @default {
       *       "market_scanner": true,
       *       "network_context": true,
       *       "asset_analyzer": true,
       *       "portfolio_layer": true,
       *       "horizons_minutes": [
       *         60
       *       ],
       *       "allow_abstain": true
       *     }
       */
      analysis: components["schemas"]["AnalysisConfig"];
      model_policy: components["schemas"]["ModelPolicy"];
      /**
       * @default {
       *       "min_source_quality": 0.65,
       *       "require_timestamps": true,
       *       "require_contradicting_evidence": true,
       *       "min_evidence_items": 2
       *     }
       */
      evidence: components["schemas"]["EvidenceRequirements"];
      /** Risk Policy Ref */
      risk_policy_ref: string;
      /** Execution Policy Ref */
      execution_policy_ref: string;
    };
    /**
     * AgentVersionCreate
     * @description Create a new version of an existing agent.
     *
     *     There is no update endpoint by design: editing an agent creates a version, it does not mutate
     *     the configuration that produced historical decisions (``MASTER_BUILD_SPEC.md`` §3, §38).
     */
    AgentVersionCreate: {
      spec: components["schemas"]["AgentSpec"];
      /** Change Summary */
      change_summary: string;
      /** @default human */
      author_kind: components["schemas"]["AuthorKind"];
    };
    /**
     * AgentVersionResponse
     * @description A version with its full specification.
     */
    AgentVersionResponse: {
      /** Agent Version Id */
      agent_version_id: string;
      /** Agent Id */
      agent_id: string;
      /** Version */
      version: number;
      /** Spec Hash */
      spec_hash: string;
      /** Prompt Hash */
      prompt_hash: string;
      /** Feature Set Version */
      feature_set_version: string;
      stage: components["schemas"]["PromotionStage"];
      approval_status: components["schemas"]["ApprovalStatus"];
      /** Approved Environments */
      approved_environments: string[];
      author_kind: components["schemas"]["AuthorKind"];
      /** Change Summary */
      change_summary: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      /** Spec */
      spec: {
        [key: string]: unknown;
      };
    };
    /** AgentVersionSummary */
    AgentVersionSummary: {
      /** Agent Version Id */
      agent_version_id: string;
      /** Agent Id */
      agent_id: string;
      /** Version */
      version: number;
      /** Spec Hash */
      spec_hash: string;
      /** Prompt Hash */
      prompt_hash: string;
      /** Feature Set Version */
      feature_set_version: string;
      stage: components["schemas"]["PromotionStage"];
      approval_status: components["schemas"]["ApprovalStatus"];
      /** Approved Environments */
      approved_environments: string[];
      author_kind: components["schemas"]["AuthorKind"];
      /** Change Summary */
      change_summary: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
    };
    /** AnalysisConfig */
    AnalysisConfig: {
      /**
       * Market Scanner
       * @default true
       */
      market_scanner: boolean;
      /**
       * Network Context
       * @default true
       */
      network_context: boolean;
      /**
       * Asset Analyzer
       * @default true
       */
      asset_analyzer: boolean;
      /**
       * Portfolio Layer
       * @default true
       */
      portfolio_layer: boolean;
      /**
       * Horizons Minutes
       * @default [
       *       60
       *     ]
       */
      horizons_minutes: number[];
      /**
       * Allow Abstain
       * @default true
       */
      allow_abstain: boolean;
    };
    /**
     * ApprovalStatus
     * @enum {string}
     */
    ApprovalStatus: "pending" | "approved" | "rejected" | "withdrawn";
    /** AuditSummary */
    AuditSummary: {
      /** Event Id */
      event_id: string;
      /** Action */
      action: string;
      /** Resource Type */
      resource_type: string;
      /** Resource Id */
      resource_id: string;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
    };
    /**
     * AuthorKind
     * @description Whether a version's changes were written by a human or generated (§38).
     * @enum {string}
     */
    AuthorKind: "human" | "ai_assisted" | "ai_generated";
    /**
     * DataFamily
     * @description Data families that carry independent freshness budgets (``MASTER_BUILD_SPEC.md`` §11.3).
     * @enum {string}
     */
    DataFamily:
      | "trades"
      | "book"
      | "candles"
      | "derivatives"
      | "onchain"
      | "defi"
      | "news"
      | "macro"
      | "reference";
    /**
     * DataPack
     * @description Explicitly enabled data families (``MASTER_BUILD_SPEC.md`` §7).
     *
     *     Packs are opt-in per agent because they carry both cost and licence entitlement (§8.3).
     * @enum {string}
     */
    DataPack:
      | "market_microstructure"
      | "price_technical"
      | "derivatives"
      | "onchain_core"
      | "stablecoins"
      | "etf_flows"
      | "tokenomics"
      | "defi"
      | "news"
      | "macro"
      | "security_events"
      | "social_attention"
      | "relative_strength";
    /**
     * DecisionState
     * @description The agent's read of the situation (``MASTER_BUILD_SPEC.md`` §6.7).
     * @enum {string}
     */
    DecisionState: "bullish" | "bearish" | "neutral" | "high_risk" | "unknown";
    /**
     * EventRiskPolicy
     * @description Behaviour around scheduled high-impact events (``MASTER_BUILD_SPEC.md`` §7.13).
     */
    "EventRiskPolicy-Input": {
      /**
       * Block New Positions Before Macro Minutes
       * @default 10
       */
      block_new_positions_before_macro_minutes: number;
      /**
       * Block New Positions After Macro Minutes
       * @default 5
       */
      block_new_positions_after_macro_minutes: number;
      /**
       * Reduce Size Pct During Event Risk
       * @default 0
       */
      reduce_size_pct_during_event_risk: number | string;
    };
    /**
     * EventRiskPolicy
     * @description Behaviour around scheduled high-impact events (``MASTER_BUILD_SPEC.md`` §7.13).
     */
    "EventRiskPolicy-Output": {
      /**
       * Block New Positions Before Macro Minutes
       * @default 10
       */
      block_new_positions_before_macro_minutes: number;
      /**
       * Block New Positions After Macro Minutes
       * @default 5
       */
      block_new_positions_after_macro_minutes: number;
      /**
       * Reduce Size Pct During Event Risk
       * @default 0
       */
      reduce_size_pct_during_event_risk: string;
    };
    /**
     * EvidenceItem
     * @description One immutable, attributable piece of evidence available to a decision.
     *
     *     ``content_hash`` makes the item verifiable after the fact: a stored decision can be replayed
     *     against exactly the evidence that produced it.
     */
    EvidenceItem: {
      /**
       * Evidence Id
       * @description ev_ id
       */
      evidence_id: string;
      kind: components["schemas"]["EvidenceKind"];
      source_class: components["schemas"]["SourceClass"];
      /** Provider */
      provider: string;
      /** Summary */
      summary: string;
      /**
       * Instruments
       * @default []
       */
      instruments: components["schemas"]["InstrumentId"][];
      /**
       * Assets
       * @default []
       */
      assets: string[];
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string;
      /**
       * Ingested At
       * Format: date-time
       */
      ingested_at: string;
      /** Source Ref */
      source_ref?: string | null;
      /** Content Hash */
      content_hash: string;
      /** Quality */
      quality: number;
      /** Confidence */
      confidence: number;
      /**
       * Is Contradictory Candidate
       * @default false
       */
      is_contradictory_candidate: boolean;
      news_event?: components["schemas"]["NewsEvent"] | null;
      /**
       * Injection Signals
       * @default []
       */
      injection_signals: string[];
      /** License Ref */
      license_ref?: string | null;
    };
    /**
     * EvidenceKind
     * @description What family of evidence this is, matching the signal families in §7.
     * @enum {string}
     */
    EvidenceKind:
      | "price_technical"
      | "order_flow"
      | "derivatives"
      | "onchain"
      | "stablecoin"
      | "etf_flow"
      | "tokenomics"
      | "defi"
      | "network_event"
      | "exchange_event"
      | "security_event"
      | "news"
      | "macro"
      | "regulation"
      | "geopolitical"
      | "social_attention"
      | "relative_strength";
    /**
     * EvidenceRequirements
     * @description What an agent must have before it is permitted to act (``MASTER_BUILD_SPEC.md`` §9).
     */
    EvidenceRequirements: {
      /**
       * Min Source Quality
       * @default 0.65
       */
      min_source_quality: number;
      /**
       * Require Timestamps
       * @default true
       */
      require_timestamps: boolean;
      /**
       * Require Contradicting Evidence
       * @default true
       */
      require_contradicting_evidence: boolean;
      /**
       * Min Evidence Items
       * @default 2
       */
      min_evidence_items: number;
    };
    /** ExecutionCandidate */
    ExecutionCandidate: {
      /** Fee Bps */
      fee_bps: number | string;
      /** Slippage Bps */
      slippage_bps: number | string;
      /** Notional Increment Usd */
      notional_increment_usd: number | string;
      /** Max Snapshot Age Ms */
      max_snapshot_age_ms: number;
      /** Max Portfolio Age Ms */
      max_portfolio_age_ms: number;
      /** Max Reconciliation Age Ms */
      max_reconciliation_age_ms: number;
      /** Max Market Age Ms */
      max_market_age_ms: number;
      /** Max Approval Age Ms */
      max_approval_age_ms: number;
    };
    /**
     * FreshnessPolicy
     * @description Maximum tolerated data age per family, in milliseconds (``MASTER_BUILD_SPEC.md`` §11.3).
     *
     *     Data freshness is part of risk (``AGENTS.md`` domain rule 5): a correct decision on stale
     *     data is still a wrong trade.
     */
    FreshnessPolicy: {
      /** Max Age Ms */
      max_age_ms: {
        [key: string]: number;
      };
      /**
       * Required Families
       * @default []
       */
      required_families: components["schemas"]["DataFamily"][];
      /**
       * Min Data Quality
       * @default 0.6
       */
      min_data_quality: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
      /** Service */
      service: string;
      /** Version */
      version: string;
    };
    /**
     * InstrumentClass
     * @description What kind of contract an instrument is.
     *
     *     Only ``SPOT`` is executable in V1 (ADR 0002). Derivatives appear here because their *data*
     *     is a first-class signal source (``MASTER_BUILD_SPEC.md`` §7.3) even though the platform does
     *     not trade them.
     * @enum {string}
     */
    InstrumentClass: "spot" | "perpetual" | "future" | "option" | "index";
    /**
     * InstrumentId
     * @description A tradable or observable instrument, unambiguous across venues and contract types.
     *
     *     Canonical string form is ``BASE-QUOTE.VENUE`` for spot, and ``BASE-QUOTE.VENUE:CLASS`` for
     *     everything else — for example ``BTC-USDT.BINANCE`` and ``BTC-USDT.BINANCE:perpetual``.
     */
    InstrumentId: {
      /** Base */
      base: string;
      /** Quote */
      quote: string;
      /**
       * Venue
       * @description Uppercase venue or data-source identifier, e.g. BINANCE, COINBASE, SIM.
       */
      venue: string;
      /** @default spot */
      instrument_class: components["schemas"]["InstrumentClass"];
    };
    /**
     * MarketRegime
     * @description Regime labels from ``MASTER_BUILD_SPEC.md`` §44.
     *
     *     The label set is closed on purpose: a model may interpret regime context, but it may not
     *     invent unbounded regime labels during execution, because downstream policy keys off them.
     * @enum {string}
     */
    MarketRegime:
      | "trend_up"
      | "trend_down"
      | "range"
      | "high_volatility"
      | "low_liquidity"
      | "deleveraging"
      | "crowded_long"
      | "crowded_short"
      | "event_risk"
      | "unknown";
    /**
     * MeResponse
     * @description Who the caller is, and what they can reach.
     *
     *     ``permissions`` is returned per workspace so the client can hide actions it cannot perform.
     *     The server re-checks every one of them — a hidden button is a usability feature, never a
     *     security control.
     */
    MeResponse: {
      /** User Id */
      user_id: string;
      /** Email */
      email: string | null;
      /** Mfa Verified */
      mfa_verified: boolean;
      /** Workspaces */
      workspaces: components["schemas"]["WorkspaceSummary"][];
      /** Permissions */
      permissions: {
        [key: string]: components["schemas"]["Permission"][];
      };
    };
    /**
     * ModelCallRecord
     * @description What the model gateway actually did, for cost accounting and reproducibility.
     *
     *     ``resolved_model_identifier`` is recorded rather than the profile alone: a routing fallback
     *     must never silently change which model produced a reproducible result (ADR 0010).
     */
    ModelCallRecord: {
      /** Model Call Id */
      model_call_id: string;
      /** Profile */
      profile: string;
      /** Resolved Model Identifier */
      resolved_model_identifier: string;
      /** Prompt Hash */
      prompt_hash: string;
      /** Input Tokens */
      input_tokens: number;
      /** Output Tokens */
      output_tokens: number;
      cost: components["schemas"]["Money"];
      /** Latency Ms */
      latency_ms: number;
      /**
       * Tool Calls
       * @default 0
       */
      tool_calls: number;
      /**
       * Schema Validation Failed
       * @default false
       */
      schema_validation_failed: boolean;
      /** Trace Id */
      trace_id?: string | null;
      /** Workspace Id */
      workspace_id?: string | null;
      /** Agent Id */
      agent_id?: string | null;
      /** Agent Version Id */
      agent_version_id?: string | null;
      /** Decision Id */
      decision_id?: string | null;
      /** Request Hash */
      request_hash?: string | null;
      /** Output Hash */
      output_hash?: string | null;
      /** Schema Hash */
      schema_hash?: string | null;
      /** Route Hash */
      route_hash?: string | null;
      /**
       * Outcome
       * @default success
       */
      outcome: string;
      /**
       * Usage Known
       * @default true
       */
      usage_known: boolean;
      /**
       * Cost Is Reservation
       * @default false
       */
      cost_is_reservation: boolean;
    };
    /** ModelPolicy */
    ModelPolicy: {
      /** @default reason_balanced */
      profile: components["schemas"]["ModelProfile"];
      /** Max Cost Per Decision Usd */
      max_cost_per_decision_usd: number | string;
      /**
       * Max Tool Calls
       * @default 12
       */
      max_tool_calls: number;
      /**
       * Max Output Tokens
       * @default 4096
       */
      max_output_tokens: number;
      /**
       * Timeout Seconds
       * @default 60
       */
      timeout_seconds: number;
    };
    /**
     * ModelProfile
     * @description Routing profiles, not model names (``MASTER_BUILD_SPEC.md`` §13.5).
     *
     *     Product behaviour must not be hard-coded to a current model name; the gateway resolves a
     *     profile to a concrete model, and the resolved identifier is recorded on the decision.
     * @enum {string}
     */
    ModelProfile:
      | "extract_fast"
      | "classify_fast"
      | "reason_balanced"
      | "reason_deep"
      | "embed";
    /**
     * Money
     * @description An amount in a specific currency.
     *
     *     Arithmetic is deliberately restrictive: adding USD to USDT is a bug, not a conversion, and
     *     this type will not quietly perform one.
     */
    Money: {
      /** Amount */
      amount: string;
      /**
       * Currency
       * @description Uppercase asset or currency code, e.g. BTC, ETH, USDT, USD.
       */
      currency: string;
    };
    /**
     * NewsEvent
     * @description A structured news event extracted from untrusted text (``MASTER_BUILD_SPEC.md`` §7.12).
     *
     *     The extraction step is where an article stops being text and becomes data. Sentiment alone
     *     is close to useless; credibility, novelty, certainty and expected horizon are what make an
     *     event actionable or not.
     */
    NewsEvent: {
      event_type: components["schemas"]["NewsEventType"];
      /**
       * Assets
       * @default []
       */
      assets: string[];
      /** Importance */
      importance: number;
      /** Sentiment */
      sentiment: number;
      /** Certainty */
      certainty: number;
      /** Novelty */
      novelty: number;
      /** Source Quality */
      source_quality: number;
      /** Expected Horizon */
      expected_horizon: string;
      /** Already Priced In Likelihood */
      already_priced_in_likelihood?: number | null;
      /**
       * Published At
       * Format: date-time
       */
      published_at: string;
      /**
       * First Seen At
       * Format: date-time
       */
      first_seen_at: string;
      /** Primary Source Ref */
      primary_source_ref?: string | null;
      /**
       * Corroborating Source Refs
       * @default []
       */
      corroborating_source_refs: string[];
    };
    /**
     * NewsEventType
     * @enum {string}
     */
    NewsEventType:
      | "regulation"
      | "enforcement"
      | "listing"
      | "delisting"
      | "partnership"
      | "funding"
      | "protocol_upgrade"
      | "outage"
      | "exploit"
      | "governance"
      | "token_unlock"
      | "macro_release"
      | "market_structure"
      | "other";
    /** Page[AgentResponse] */
    Page_AgentResponse_: {
      /** Items */
      items: components["schemas"]["AgentResponse"][];
      /** Next Cursor */
      next_cursor?: string | null;
      /**
       * Has More
       * @default false
       */
      has_more: boolean;
    };
    /** Page[AgentVersionSummary] */
    Page_AgentVersionSummary_: {
      /** Items */
      items: components["schemas"]["AgentVersionSummary"][];
      /** Next Cursor */
      next_cursor?: string | null;
      /**
       * Has More
       * @default false
       */
      has_more: boolean;
    };
    /** Page[AuditSummary] */
    Page_AuditSummary_: {
      /** Items */
      items: components["schemas"]["AuditSummary"][];
      /** Next Cursor */
      next_cursor?: string | null;
      /**
       * Has More
       * @default false
       */
      has_more: boolean;
    };
    /** Page[PaperAccountView] */
    Page_PaperAccountView_: {
      /** Items */
      items: components["schemas"]["PaperAccountView"][];
      /** Next Cursor */
      next_cursor?: string | null;
      /**
       * Has More
       * @default false
       */
      has_more: boolean;
    };
    /** Page[PaperPolicyBundleResponse] */
    Page_PaperPolicyBundleResponse_: {
      /** Items */
      items: components["schemas"]["PaperPolicyBundleResponse"][];
      /** Next Cursor */
      next_cursor?: string | null;
      /**
       * Has More
       * @default false
       */
      has_more: boolean;
    };
    /** Page[RunSummary] */
    Page_RunSummary_: {
      /** Items */
      items: components["schemas"]["RunSummary"][];
      /** Next Cursor */
      next_cursor?: string | null;
      /**
       * Has More
       * @default false
       */
      has_more: boolean;
    };
    /** PaperAccountView */
    PaperAccountView: {
      /** Account Id */
      account_id: string;
      /** Sequence */
      sequence: number;
      /** State Hash */
      state_hash: string;
      /**
       * Committed At
       * Format: date-time
       */
      committed_at: string;
      portfolio: components["schemas"]["PortfolioSnapshot"];
      fees_paid: components["schemas"]["Money"];
    };
    /** PaperActivationAssessmentCreate */
    PaperActivationAssessmentCreate: {
      /** Bundle Id */
      bundle_id: string;
      /** Approval Id */
      approval_id: string;
      /** Evaluation Run Id */
      evaluation_run_id: string;
      /** Agent Spec Hash */
      agent_spec_hash: string;
      /** Risk Hash */
      risk_hash: string;
      /** Execution Hash */
      execution_hash: string;
      /** Evaluation Input Hash */
      evaluation_input_hash: string;
      /** Reason */
      reason: string;
    };
    /** PaperActivationAssessmentResponse */
    PaperActivationAssessmentResponse: {
      /** Assessment Id */
      assessment_id: string;
      /** Workspace Id */
      workspace_id: string;
      /** Agent Id */
      agent_id: string;
      /** Agent Version Id */
      agent_version_id: string;
      /** Version */
      version: number;
      /** Bundle Id */
      bundle_id: string;
      /** Approval Id */
      approval_id: string;
      /** Evaluation Run Id */
      evaluation_run_id: string;
      /** Agent Spec Hash */
      agent_spec_hash: string;
      /** Risk Hash */
      risk_hash: string;
      /** Execution Hash */
      execution_hash: string;
      /** Evaluation Input Hash */
      evaluation_input_hash: string;
      /** Evaluation Output Hash */
      evaluation_output_hash: string | null;
      /** Providers */
      providers: string[];
      /** License Refs */
      license_refs: string[];
      /** Entitlement Event Refs */
      entitlement_event_refs: components["schemas"]["PaperActivationEntitlementRef"][];
      /** Gate Results */
      gate_results: components["schemas"]["PaperActivationGateResult"][];
      /**
       * Decision
       * @enum {string}
       */
      decision: "blocked" | "eligible";
      /** Reason */
      reason: string;
      /** Assessed By */
      assessed_by: string;
      /**
       * Assessed At
       * Format: date-time
       */
      assessed_at: string;
      /**
       * Activation Status
       * @default inactive
       * @constant
       */
      activation_status: "inactive";
      /**
       * Execution Enabled
       * @default false
       * @constant
       */
      execution_enabled: false;
    };
    /** PaperActivationEntitlementRef */
    PaperActivationEntitlementRef: {
      /** Event Id */
      event_id: string;
      /** Event Hash */
      event_hash: string;
      /**
       * Scope
       * @enum {string}
       */
      scope: "platform" | "workspace";
      /** Provider */
      provider: string;
      /** License Ref */
      license_ref: string;
    };
    /** @enum {string} */
    PaperActivationGateName:
      | "policy_approval_integrity"
      | "version_policy_binding"
      | "evaluation_completion"
      | "evaluation_version_binding"
      | "promotable_evidence"
      | "provider_entitlement"
      | "activation_support";
    /** PaperActivationGateResult */
    PaperActivationGateResult: {
      gate: components["schemas"]["PaperActivationGateName"];
      /** Passed */
      passed: boolean;
      /** Reason Code */
      reason_code: string;
    };
    /**
     * PaperPolicyApprovalCreate
     * @description Approve the exact policy documents recorded by an advancing review.
     */
    PaperPolicyApprovalCreate: {
      /** Review Id */
      review_id: string;
      /** Reason */
      reason: string;
      /** Risk Hash */
      risk_hash: string;
      /** Execution Hash */
      execution_hash: string;
    };
    /** PaperPolicyApprovalResponse */
    PaperPolicyApprovalResponse: {
      /** Approval Id */
      approval_id: string;
      /** Review Id */
      review_id: string;
      /** Bundle Id */
      bundle_id: string;
      /** Workspace Id */
      workspace_id: string;
      /** Reason */
      reason: string;
      /** Risk Hash */
      risk_hash: string;
      /** Execution Hash */
      execution_hash: string;
      /** Approved By */
      approved_by: string;
      /**
       * Approved At
       * Format: date-time
       */
      approved_at: string;
      /**
       * Approval Status
       * @default approved
       * @constant
       */
      approval_status: "approved";
      /**
       * Activation Status
       * @default inactive
       * @constant
       */
      activation_status: "inactive";
      /**
       * Execution Enabled
       * @default false
       * @constant
       */
      execution_enabled: false;
    };
    /** PaperPolicyBundleCreate */
    PaperPolicyBundleCreate: {
      limits: components["schemas"]["RiskLimits-Input"];
      freshness: components["schemas"]["FreshnessPolicy"];
      /**
       * @default {
       *       "block_new_positions_before_macro_minutes": 10,
       *       "block_new_positions_after_macro_minutes": 5,
       *       "reduce_size_pct_during_event_risk": "0"
       *     }
       */
      event_risk: components["schemas"]["EventRiskPolicy-Input"];
      execution: components["schemas"]["ExecutionCandidate"];
      /** Reason */
      reason: string;
    };
    /** PaperPolicyBundleResponse */
    PaperPolicyBundleResponse: {
      /** Bundle Id */
      bundle_id: string;
      /** Workspace Id */
      workspace_id: string;
      risk: components["schemas"]["RiskPolicy"];
      execution: components["schemas"]["RiskExecutionPolicy"];
      /** Risk Hash */
      risk_hash: string;
      /** Execution Hash */
      execution_hash: string;
      /**
       * Approval Status
       * @enum {string}
       */
      approval_status:
        "unapproved" | "reviewed" | "changes_requested" | "approved";
      /**
       * Execution Enabled
       * @default false
       * @constant
       */
      execution_enabled: false;
      /** Reason */
      reason: string;
      /** Created By */
      created_by: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * PaperPolicyReviewCreate
     * @description A second person's recommendation; never an execution authorization.
     */
    PaperPolicyReviewCreate: {
      /**
       * Recommendation
       * @enum {string}
       */
      recommendation: "advance_to_evaluation" | "changes_requested";
      /** Reason */
      reason: string;
      /** Risk Hash */
      risk_hash: string;
      /** Execution Hash */
      execution_hash: string;
    };
    /** PaperPolicyReviewResponse */
    PaperPolicyReviewResponse: {
      /** Review Id */
      review_id: string;
      /** Bundle Id */
      bundle_id: string;
      /** Workspace Id */
      workspace_id: string;
      /**
       * Recommendation
       * @enum {string}
       */
      recommendation: "advance_to_evaluation" | "changes_requested";
      /** Reason */
      reason: string;
      /** Risk Hash */
      risk_hash: string;
      /** Execution Hash */
      execution_hash: string;
      /** Reviewed By */
      reviewed_by: string;
      /**
       * Reviewed At
       * Format: date-time
       */
      reviewed_at: string;
      /**
       * Approval Status
       * @enum {string}
       */
      approval_status: "reviewed" | "changes_requested" | "approved";
      /**
       * Execution Enabled
       * @default false
       * @constant
       */
      execution_enabled: false;
    };
    /**
     * Permission
     * @description Discrete capabilities. Add, never repurpose.
     * @enum {string}
     */
    Permission:
      | "workspace:read"
      | "workspace:update"
      | "workspace:delete"
      | "member:read"
      | "member:invite"
      | "member:remove"
      | "agent:read"
      | "agent:create"
      | "agent:update"
      | "agent:archive"
      | "agent:promote"
      | "risk_policy:read"
      | "risk_policy:write"
      | "run:read"
      | "run:start"
      | "run:stop"
      | "audit:read"
      | "exchange_connection:read"
      | "exchange_connection:write";
    /**
     * PlatformModeResponse
     * @description The authoritative trading-mode state for the whole platform.
     */
    PlatformModeResponse: {
      /**
       * Live Trading Enabled
       * @description Always false in this release. Live execution is gated on MASTER_BUILD_SPEC.md §47 and ADR 0001.
       * @default false
       * @constant
       */
      live_trading_enabled: false;
      /** Default Trading Mode */
      default_trading_mode: string;
      /** Environment */
      environment: string;
      /** Disclosure */
      disclosure: string;
    };
    /**
     * PortfolioSnapshot
     * @description Point-in-time portfolio state used by the portfolio and risk layers.
     */
    PortfolioSnapshot: {
      /**
       * Workspace Id
       * @description ws_ id
       */
      workspace_id: string;
      mode: components["schemas"]["TradingMode"];
      /**
       * As Of
       * Format: date-time
       */
      as_of: string;
      /** Base Currency */
      base_currency: string;
      cash: components["schemas"]["Money"];
      reserved_cash: components["schemas"]["Money"];
      /**
       * Positions
       * @default []
       */
      positions: components["schemas"]["Position"][];
      realized_pnl_today: components["schemas"]["Money"];
      unrealized_pnl: components["schemas"]["Money"];
      equity: components["schemas"]["Money"];
      gross_exposure: components["schemas"]["Money"];
      net_exposure: components["schemas"]["Money"];
      peak_equity: components["schemas"]["Money"];
      /**
       * Open Order Count
       * @default 0
       */
      open_order_count: number;
      /**
       * Is Reconciled
       * @default true
       */
      is_reconciled: boolean;
      /** Reconciled At */
      reconciled_at?: string | null;
    };
    /**
     * Position
     * @description A held position. Negative quantity represents short exposure (not executable in V1).
     */
    Position: {
      instrument_id: components["schemas"]["InstrumentId"];
      quantity: components["schemas"]["Quantity"];
      average_entry_price?: components["schemas"]["Price"] | null;
      mark_price?: components["schemas"]["Price"] | null;
      realized_pnl: components["schemas"]["Money"];
      unrealized_pnl: components["schemas"]["Money"];
      /** Opened At */
      opened_at?: string | null;
      /** Network */
      network?: string | null;
    };
    /**
     * Prediction
     * @description A quantified expectation with explicit uncertainty.
     */
    Prediction: {
      /** Expected Return Bps */
      expected_return_bps: number;
      /** Confidence */
      confidence: number;
      /** Uncertainty */
      uncertainty: number;
      /** Horizon Minutes */
      horizon_minutes: number;
    };
    /**
     * Price
     * @description A price expressed as quote currency per one unit of the base asset.
     */
    Price: {
      /** Value */
      value: string;
      /**
       * Base
       * @description Uppercase asset or currency code, e.g. BTC, ETH, USDT, USD.
       */
      base: string;
      /**
       * Quote
       * @description Uppercase asset or currency code, e.g. BTC, ETH, USDT, USD.
       */
      quote: string;
    };
    /**
     * PromotionStage
     * @description Promotion pipeline stages (``MASTER_BUILD_SPEC.md`` §12.6).
     *
     *     A failed gate produces a new version; it never rewrites history.
     * @enum {string}
     */
    PromotionStage:
      | "draft"
      | "historical_backtest"
      | "out_of_sample"
      | "paper_candidate"
      | "paper_observation"
      | "live_eligible"
      | "live_limited"
      | "live_expanded";
    /**
     * ProposedAction
     * @description The only actions a model may propose (``MASTER_BUILD_SPEC.md`` §6.6).
     *
     *     This is a closed set on purpose. A model cannot propose "withdraw", "transfer", "change
     *     risk policy", or any free-form instruction, because those words have no representation here.
     * @enum {string}
     */
    ProposedAction: "buy" | "sell" | "reduce" | "close" | "hold" | "no_trade";
    /**
     * Quantity
     * @description A quantity of an asset. Negative values represent short exposure.
     */
    Quantity: {
      /** Value */
      value: string;
      /**
       * Asset
       * @description Uppercase asset or currency code, e.g. BTC, ETH, USDT, USD.
       */
      asset: string;
    };
    /** ReadinessResponse */
    ReadinessResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: "ready" | "degraded";
      /** Checks */
      checks: {
        [key: string]: "ok" | "unavailable" | "not_configured";
      };
    };
    /** RehearsalLaunch */
    RehearsalLaunch: {
      /** Run Id */
      run_id: string;
      /** Input Hash */
      input_hash: string;
      /**
       * Dispatch State
       * @enum {string}
       */
      dispatch_state: "dispatched" | "queued";
      /** Replayed */
      replayed: boolean;
      /**
       * Input Kind
       * @default synthetic_rehearsal
       * @enum {string}
       */
      input_kind: "synthetic_rehearsal" | "testnet_rehearsal";
      /**
       * Execution Enabled
       * @default false
       * @constant
       */
      execution_enabled: false;
    };
    /**
     * RiskExecutionPolicy
     * @description Local USD-spot MARKET/IOC only. Assumptions are operator configuration, not venue facts.
     */
    RiskExecutionPolicy: {
      /** Execution Policy Id */
      execution_policy_id: string;
      /** Version */
      version: string;
      /** Fee Bps */
      fee_bps: string;
      /** Slippage Bps */
      slippage_bps: string;
      /** Notional Increment Usd */
      notional_increment_usd: string;
      /** Max Snapshot Age Ms */
      max_snapshot_age_ms: number;
      /** Max Portfolio Age Ms */
      max_portfolio_age_ms: number;
      /** Max Reconciliation Age Ms */
      max_reconciliation_age_ms: number;
      /** Max Market Age Ms */
      max_market_age_ms: number;
      /** Max Approval Age Ms */
      max_approval_age_ms: number;
    };
    /**
     * RiskLimits
     * @description Exposure and loss limits. Percentages are of portfolio equity unless stated.
     */
    "RiskLimits-Input": {
      /** Max Gross Exposure Pct */
      max_gross_exposure_pct: number | string;
      /** Max Single Asset Exposure Pct */
      max_single_asset_exposure_pct: number | string;
      /** Max Network Exposure Pct */
      max_network_exposure_pct: number | string;
      /** Max Open Positions */
      max_open_positions: number;
      /** Max Daily Loss Pct */
      max_daily_loss_pct: number | string;
      /** Max Drawdown Pct */
      max_drawdown_pct: number | string;
      /** Min Liquidity Usd */
      min_liquidity_usd: number | string;
      /** Max Spread Bps */
      max_spread_bps: number;
      /** Min Order Notional Usd */
      min_order_notional_usd: number | string;
      /** Max Order Notional Usd */
      max_order_notional_usd: number | string;
      /**
       * Min Edge Over Cost Bps
       * @default 5
       */
      min_edge_over_cost_bps: number;
    };
    /**
     * RiskLimits
     * @description Exposure and loss limits. Percentages are of portfolio equity unless stated.
     */
    "RiskLimits-Output": {
      /** Max Gross Exposure Pct */
      max_gross_exposure_pct: string;
      /** Max Single Asset Exposure Pct */
      max_single_asset_exposure_pct: string;
      /** Max Network Exposure Pct */
      max_network_exposure_pct: string;
      /** Max Open Positions */
      max_open_positions: number;
      /** Max Daily Loss Pct */
      max_daily_loss_pct: string;
      /** Max Drawdown Pct */
      max_drawdown_pct: string;
      /** Min Liquidity Usd */
      min_liquidity_usd: string;
      /** Max Spread Bps */
      max_spread_bps: number;
      /** Min Order Notional Usd */
      min_order_notional_usd: string;
      /** Max Order Notional Usd */
      max_order_notional_usd: string;
      /**
       * Min Edge Over Cost Bps
       * @default 5
       */
      min_edge_over_cost_bps: number;
    };
    /**
     * RiskPolicy
     * @description An immutable, versioned risk policy.
     *
     *     Policies are referenced by id from an ``AgentSpec`` and recorded on every evaluation, so a
     *     historical rejection can be explained with the policy that actually applied.
     */
    RiskPolicy: {
      /**
       * Risk Policy Id
       * @description rp_ id
       */
      risk_policy_id: string;
      /** Workspace Id */
      workspace_id?: string | null;
      /** Version */
      version: number;
      scope: components["schemas"]["RiskScope"];
      limits: components["schemas"]["RiskLimits-Output"];
      freshness: components["schemas"]["FreshnessPolicy"];
      /**
       * @default {
       *       "block_new_positions_before_macro_minutes": 10,
       *       "block_new_positions_after_macro_minutes": 5,
       *       "reduce_size_pct_during_event_risk": "0"
       *     }
       */
      event_risk: components["schemas"]["EventRiskPolicy-Output"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by: string;
      /** Content Hash */
      content_hash: string;
    };
    /**
     * RiskScope
     * @description The limit hierarchy (``MASTER_BUILD_SPEC.md`` §11.2), most general first.
     * @enum {string}
     */
    RiskScope:
      | "global"
      | "workspace"
      | "portfolio"
      | "network"
      | "agent"
      | "asset"
      | "order";
    /**
     * Role
     * @description Workspace roles, least privileged last.
     *
     *     ``OWNER`` and ``ADMIN`` are distinguished because deleting a workspace, or removing its last
     *     owner, should not be available to everyone who can administer agents.
     * @enum {string}
     */
    Role: "owner" | "admin" | "member" | "viewer";
    /** RunInspection */
    RunInspection: {
      /** Run Id */
      run_id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "agent" | "backtest" | "health" | "supervision";
      /**
       * Input Kind
       * @default recorded
       * @enum {string}
       */
      input_kind: "recorded" | "synthetic_rehearsal" | "testnet_rehearsal";
      /**
       * Status
       * @enum {string}
       */
      status: "queued" | "running" | "completed" | "refused" | "uncertain";
      /** Input Hash */
      input_hash: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Stages */
      stages: components["schemas"]["StageSummary"][];
      /** Decisions */
      decisions: components["schemas"]["AgentDecision"][];
      /** Evidence */
      evidence: components["schemas"]["EvidenceItem"][];
      /** Reason Codes */
      reason_codes: string[];
    };
    /** RunSummary */
    RunSummary: {
      /** Run Id */
      run_id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "agent" | "backtest" | "health" | "supervision";
      /**
       * Input Kind
       * @default recorded
       * @enum {string}
       */
      input_kind: "recorded" | "synthetic_rehearsal" | "testnet_rehearsal";
      /**
       * Status
       * @enum {string}
       */
      status: "queued" | "running" | "completed" | "refused" | "uncertain";
      /** Input Hash */
      input_hash: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ScheduleConfig */
    ScheduleConfig: {
      /** Decision Interval Seconds */
      decision_interval_seconds: number;
      /**
       * Event Triggers
       * @default []
       */
      event_triggers: string[];
      /**
       * Max Decisions Per Day
       * @default 96
       */
      max_decisions_per_day: number;
    };
    /**
     * SignalScores
     * @description Per-family signal contributions, each in [-1, 1].
     *
     *     Signal families rather than raw indicators: dumping hundreds of indicators into a model
     *     produces confident noise (``MASTER_BUILD_SPEC.md`` §7).
     */
    SignalScores: {
      /**
       * Price
       * @default 0
       */
      price: number;
      /**
       * Order Flow
       * @default 0
       */
      order_flow: number;
      /**
       * Derivatives
       * @default 0
       */
      derivatives: number;
      /**
       * Liquidity
       * @default 0
       */
      liquidity: number;
      /**
       * Onchain
       * @default 0
       */
      onchain: number;
      /**
       * Tokenomics
       * @default 0
       */
      tokenomics: number;
      /**
       * Defi
       * @default 0
       */
      defi: number;
      /**
       * Events
       * @default 0
       */
      events: number;
      /**
       * News
       * @default 0
       */
      news: number;
      /**
       * Macro
       * @default 0
       */
      macro: number;
    };
    /**
     * SourceClass
     * @description Source classes from ``MASTER_BUILD_SPEC.md`` §42.
     *
     *     Source class informs confidence. It never establishes truth: an official account can be
     *     compromised, and a wire service can be wrong.
     * @enum {string}
     */
    SourceClass:
      | "official_primary"
      | "major_wire"
      | "specialist_publication"
      | "project_social"
      | "unverified_social"
      | "market_data"
      | "onchain_data"
      | "derived_feature"
      | "internal_model";
    /** StageSummary */
    StageSummary: {
      /** Stage */
      stage: string;
      /**
       * Status
       * @enum {string}
       */
      status: "started" | "completed" | "refused" | "uncertain";
      /** Output Hash */
      output_hash: string | null;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      /** Finished At */
      finished_at: string | null;
    };
    /**
     * TradingMode
     * @description The four product modes (``MASTER_BUILD_SPEC.md`` §5).
     *
     *     ``LIVE`` exists in the type system so that code can reason about it, and is refused at
     *     runtime unless the live gate is open (ADR 0001).
     * @enum {string}
     */
    TradingMode: "research" | "backtest" | "paper" | "live";
    /** UniverseConfig */
    UniverseConfig: {
      /** Instruments */
      instruments: components["schemas"]["InstrumentId"][];
      /** @default spot */
      market_type: components["schemas"]["InstrumentClass"];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WorkspaceCreate */
    WorkspaceCreate: {
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /** WorkspaceResponse */
    WorkspaceResponse: {
      /** Workspace Id */
      workspace_id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      role: components["schemas"]["Role"];
    };
    /** WorkspaceSummary */
    WorkspaceSummary: {
      /** Workspace Id */
      workspace_id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      role: components["schemas"]["Role"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  readyz_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
    };
  };
  platform_mode_v1_platform_mode_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlatformModeResponse"];
        };
      };
    };
  };
  me_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
    };
  };
  list_workspaces_v1_workspaces_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceSummary"][];
        };
      };
    };
  };
  create_workspace_v1_workspaces_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkspaceCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_workspace_v1_workspaces__workspace_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_agents_v1_workspaces__workspace_id__agents_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
        include_archived?: boolean;
      };
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_AgentResponse_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_agent_v1_workspaces__workspace_id__agents_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_agent_v1_workspaces__workspace_id__agents__agent_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        agent_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  archive_agent_v1_workspaces__workspace_id__agents__agent_id__delete: {
    parameters: {
      query?: {
        reason?: string;
      };
      header?: never;
      path: {
        agent_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_versions_v1_workspaces__workspace_id__agents__agent_id__versions_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path: {
        agent_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_AgentVersionSummary_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_version_v1_workspaces__workspace_id__agents__agent_id__versions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        agent_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgentVersionCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentVersionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_version_v1_workspaces__workspace_id__agents__agent_id__versions__version__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        agent_id: string;
        version: number;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentVersionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  runs_v1_workspaces__workspace_id__runs_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_RunSummary_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  run_detail_v1_workspaces__workspace_id__runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunInspection"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  accounts_v1_workspaces__workspace_id__paper_accounts_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_PaperAccountView_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  audit_v1_workspaces__workspace_id__audit_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_AuditSummary_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  launch_rehearsal_v1_workspaces__workspace_id__agents__agent_id__versions__version__rehearsals_post: {
    parameters: {
      query?: {
        source?: "synthetic" | "binance_testnet";
      };
      header?: never;
      path: {
        agent_id: string;
        version: number;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RehearsalLaunch"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_paper_policy_bundles_v1_workspaces__workspace_id__paper_policy_bundles_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_PaperPolicyBundleResponse_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_paper_policy_bundle_v1_workspaces__workspace_id__paper_policy_bundles_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaperPolicyBundleCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaperPolicyBundleResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_paper_policy_bundle_v1_workspaces__workspace_id__paper_policy_bundles__bundle_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundle_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaperPolicyBundleResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_paper_policy_review_v1_workspaces__workspace_id__paper_policy_bundles__bundle_id__review_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundle_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaperPolicyReviewResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  review_paper_policy_bundle_v1_workspaces__workspace_id__paper_policy_bundles__bundle_id__review_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundle_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaperPolicyReviewCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaperPolicyReviewResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_paper_policy_approval_v1_workspaces__workspace_id__paper_policy_bundles__bundle_id__approval_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundle_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaperPolicyApprovalResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approve_paper_policy_bundle_v1_workspaces__workspace_id__paper_policy_bundles__bundle_id__approval_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        bundle_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaperPolicyApprovalCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaperPolicyApprovalResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  assess_paper_activation_v1_workspaces__workspace_id__agents__agent_id__versions__version__paper_activation_assessments_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        agent_id: string;
        version: number;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaperActivationAssessmentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaperActivationAssessmentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_paper_activation_assessment_v1_workspaces__workspace_id__agents__agent_id__versions__version__paper_activation_assessments__assessment_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        agent_id: string;
        version: number;
        assessment_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaperActivationAssessmentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
